### ISSUE TITLE
labels

### ISSUE THREAD

**Issue by May-sysu** [PRBonn/LiDAR-MOS#11]
can we predict the moving object without lables?

**Comment by Chen-Xieyuanli** [comment]
Hey @May-sysu, thanks for following our work. Our method currently using the proposed binary labels to achieve MOS.
If you want to remove dynamics without using labels, you may have a look at the map-based approaches, which can also detect moving objects without training.

**Comment by May-sysu** [comment]
yep，i know that。however, supervised classification is out-performer.  can we generate the moving object predictions with pretrained model in different scene？for example, we use pretrained model based on kitti datasets to predict the moving object in the mining area, like transfer application. and what do we need to focus on ? thanks for your answer

**Comment by Chen-Xieyuanli** [comment]
Good idea! We didn't test it so far. You may give it a try. The only problem I see here is that if the types of LIDAR sensors change, it usually cannot generalize very well.

**Comment by Chen-Xieyuanli** [comment]
Hey @May-sysu, thanks for the suggestion again! Since this is more about future work, I therefore would like to close this issue. If you are interested in this topic, we could discuss it further via email.

**Comment by May-sysu** [comment]
thanks for your generosity。after converting kitti-64 to kitti-16, this algorithm still works well。however, in the mining area, there is no accurate pose information ,which is a great blow to it because of residual image. whatever，i think this light algorithm maybe is better in the object detection.

**Comment by Chen-Xieyuanli** [comment]
Great to know that it works with different types of LIDAR sensors. We could also discuss this more while WeChat. My WeChat number is : Chen_Xieyuanli 

I will appreciate it if you could also star this repo if you find it useful. Thanks!
