### ISSUE TITLE
How to construct Map using LiDAR-MOS framework?

### ISSUE THREAD

**Issue by chowkamlee81** [PRBonn/LiDAR-MOS#13]
How to construct Map using LiDAR-MOS framework? Kindly help

**Comment by Chen-Xieyuanli** [comment]
Hey @chowkamlee81, thanks for using our code! We currently aggregate the cleaned point cloud directly to get the static map.
You could of course use the cleaned data as the input to any mapping method and generate a static map.

**Comment by Chen-Xieyuanli** [comment]
A similar question was asked in #14. We so far didn't release the visualization of the aggregated point cloud and plan to release the script later.

**Comment by Chen-Xieyuanli** [comment]
People already use our LiDAR-MOS together with different mapping methods, I would like to close this issue. Feel free to reopen it if needed.
