### ISSUE TITLE
关于测试自己的数据集的问题

### ISSUE THREAD

**Issue by ferrari700** [PRBonn/LiDAR-MOS#31]
您好，请问我是否可以使用您的pretrained model测试自己的数据集，是否需要提供人工标注的label以及对自己的数据集进行training

**Comment by Chen-Xieyuanli** [comment]
@ferrari700, 我们没有尝试过，欢迎你进行尝试，通常情况下深度学习模型需要在新数据集上进行微调，如果激光雷达型号不同可能性能会不佳，请参看#19
