### ISSUE TITLE
使用vlp32线数据测试动态物体检测,绝大部分点云被认为是动态物体

### ISSUE THREAD

**Issue by ypfsmile** [PRBonn/LiDAR-MOS#34]
您好，最近使用您给出的预训练模型测试自己的vlp-32线激光雷达数据，数据格式仿照示例数据已经转换完毕，同时生成了residual_image，将其作为valid数据集测试时，发现得到的绝大部分点云（90%）被认为是动态物体，请问下有可能是什么原因导致呢？

**Comment by Chen-Xieyuanli** [comment]
Hey @ypfsmile 感谢尝试我们的代码！

这个问题和是 #19 , #31 类似的。

我们提供的预训练的模型使用的是64线激光雷达数据进行训练的，在32线激光雷达数据上性能不佳的原因可能是：1，不同传感器之间邻域距离太大了，64线激光和32线激光视野不一样，观测得到的数据分布有很大的区别，2，测试环境与训练环境差别非常大。预训练的模型泛化能力不行。

可能的解决方案是标记少量32线数据动态物体分割标签，在自己的数据集上进行fine-tune，或者针对自己的传感器数据及重新训练一个模型。

为了大家可以集中讨论类似问题，我推荐你可以专注#19 并把你的结果和问题分享给大家，因此我将关闭这个问题。

**Comment by ypfsmile** [comment]
好的 感谢！

**Comment by noobth1nker** [comment]
> 好的 感谢！

您好，请问您有没有继续这项工作呢？我也想用我的16线激光雷达试试

**Comment by noobth1nker** [comment]
@ypfsmile 您好，请问您有没有继续这项工作呢？我也想在我的16线激光雷达上试试
