### ISSUE TITLE
Issue with trying to train on multiple gpus

### ISSUE THREAD

**Issue by maneekwant** [PRBonn/LiDAR-MOS#35]
Hello! 
I was trying to train on multiple gpus and and was facing an issue. When I ran the script, I got an error message: 

RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([4]) and output[0] has a shape of torch.Size([1]).

This happens in the trainer.py script on line 389: 
    loss_m.backward(idx)

I was trying to train on 4 gpus, and so I assumed that was why grad_output[0] has a shape of torch.Size([4]), but the loss_m output from line 384 has a shape of torch.Size([1]): 
    loss_m = criterion(torch.log(output.clamp(min=1e-8)), proj_labels) + self.ls(output, proj_labels.long())

Do you have an idea of what might be causing the issue? Thank you in advance for your help!

**Comment by Chen-Xieyuanli** [comment]
Hey @maneekwant, thanks for using our code!
This issue is probably caused by the incompatible PyTorch version.
You may find more information here: [PyTorch mismatching](https://discuss.pytorch.org/t/how-to-fix-mismatch-in-shape-when-using-backward-function/58865).
We are using Version: 1.5.1+cu101.
