### ISSUE TITLE
error when evaluate iou

### ISSUE THREAD

**Issue by immaturehaan** [PRBonn/LiDAR-MOS#37]
hello, I try to eval iou after inferring them. For this example, I try in sequence 08.
I got this error.
``` 
evaluating label  /mnt/dataset/sequences/08/labels/000000.label with /mnt/result/infer_0108/sequences/08/predictions/000000.label
Traceback (most recent call last):
  File "evaluate_iou.py", line 176, in <module>
    label.open_scan(scan_file)
TypeError: open_scan() missing 2 required positional arguments: 'from_pose' and 'to_pose'
```
Can you help me? Thank you so much.

**Comment by Chen-Xieyuanli** [comment]
Hey @immaturehaan, thanks for using our code.

It seems like a data loading problem. You may double-check your data folder structure and the reference is here: https://github.com/PRBonn/LiDAR-MOS/tree/main/data#readme
