### ISSUE TITLE
Generating Residual Images for Inference

### ISSUE THREAD

**Issue by boazMgm** [PRBonn/LiDAR-MOS#42]
Hi,
Say that I'm interesting in using the pretrained model with my own dataset only for inference in the first stage.
Do I have to prepare the residual images beforehand or does the model generates them automatically?
assuming I want to use residual images (residual: True).

Thanks :)

**Comment by MaxChanger** [comment]
Yes, you cloud see [utils/gen_residual_images.py](https://github.com/PRBonn/LiDAR-MOS/blob/main/utils/gen_residual_images.py) for more information.

**Comment by Chen-Xieyuanli** [comment]
Hi @boazMgm, as @MaxChanger said, you need to generate residual images using our script. You could also integrate it into your online pipeline, but so far we don't have a plan to do that.
