### ISSUE TITLE
Labels Files while Inferring

### ISSUE THREAD

**Issue by boazMgm** [PRBonn/LiDAR-MOS#44]
Hi,
while trying to infer my dataset the code fails at the start with this error:
"File "../..//tasks/semantic/dataset/kitti/parser.py", line 197, in __init__
    assert(len(scan_files) == len(label_files))"

I think there is something basic that I'm missing here.
if the purpose of the inference is to create the label files (predictions), then why it tries to locate them at the beginning?
Thanks

**Comment by Chen-Xieyuanli** [comment]
Hey @boazMgm, the label_files here are the ground truth labels for evaluations. I guess you are using the pipeline of training. You may check the inferring pipeline.

**Comment by boazMgm** [comment]
Thanks for the reply.
The error occurred while running infer.py file.

**Comment by Chen-Xieyuanli** [comment]
> 

Please check which split you are using, if it's the sequences of training, the parser will check the ground truth labels. For testing, there are no ground truth labels thus no checking there.

We stick to the SemanticKitti parser, and it may not be the best setup.

**Comment by boazMgm** [comment]
Thanks!
