### ISSUE TITLE
How to visualize the ground truth labels?

### ISSUE THREAD

**Issue by LiXiang0021** [PRBonn/LiDAR-MOS#57]

**Comment by Chen-Xieyuanli** [comment]
Hey @LiXiang0021, nice to hear from you again.

You could directly use our visual mos to visualize the ground truth by setting prediction path as the gt folder https://github.com/PRBonn/LiDAR-MOS/blob/main/utils/visualize_mos.py

You could also use our new visualizer here: https://github.com/PRBonn/auto-mos/blob/main/vis_mos_results.py
which show the true positive, false positive, false negative using both predictions and gt labels.
