### ISSUE TITLE
How to export the dmo video?

### ISSUE THREAD

**Issue by LiXiang0021** [PRBonn/LiDAR-MOS#58]
how to export the demo video as a mp4 or mkv file?
Thanks a lot!

**Comment by Chen-Xieyuanli** [comment]
Hey @LiXiang0021, you could use our new visualizer here: https://github.com/PRBonn/auto-mos/blob/main/vis_mos_results.py

**Comment by LiXiang0021** [comment]
Thanks for your great work!
