### ISSUE TITLE
关于lidar-mos

### ISSUE THREAD

**Issue by yuhang9803** [PRBonn/LiDAR-MOS#7]
感谢您做出的如此优秀的工作！我想请问该算法可以直接只对一个bag包进行操作吗，然后由此获取一个去除了动态物体的bag包，这样就可以有更多的适用性了？

**Comment by Chen-Xieyuanli** [comment]
Hey @yuhang9803, 感谢你的建议！我们目前还有很多其他工作正在开展，暂时没有计划写ROS的接口，以后可能会考虑添加。
