### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by ghost** [PRBonn/LiDAR-MOS#72]
Dear author. I want to know how long does it take for you to training data using salsanext and what is the max_epochs you have set
I am trying to train the data myself. I don't know if it's due to my environment that the speed is so slow.
I havea 3090 GPU, CUDA11.0 pytorch1.7 TensorFlow2.4.0 in batch_size=10. the program shows that the remaining time is approximately 5 days and 12 hours.

**Comment by MaxChanger** [comment]
Some simple references,  residual_image = 8, batch_size=12, 3*3090, training time is about 4d10h.

**Comment by MaxChanger** [comment]
You can refer to this to speed up training, but the performance may be slightly worse than using full data.
https://github.com/haomo-ai/MotionSeg3D/blob/ce43ed4f4f8b693c01854be046b00eaf6ed88cf9/common/dataset/kitti/parser.py#L215-L217

**Comment by ghost** [comment]
> You can refer to this to speed up training, but the performance may be slightly worse than using full data. https://github.com/haomo-ai/MotionSeg3D/blob/ce43ed4f4f8b693c01854be046b00eaf6ed88cf9/common/dataset/kitti/parser.py#L215-L217

Thanks
