### ISSUE TITLE
使用 Question about the usage details of LiDAR-MOS

### ISSUE THREAD

**Issue by whuzs** [PRBonn/LiDAR-MOS#9]
您好, 我想问一下, LiDAR-MOS的使用是需要定位信息的输入以及连续帧的数据吗?还是说可以对单帧进行处理?谢谢

**Comment by Chen-Xieyuanli** [comment]
LiDAR-MOS使用过去连续帧信息来对当前帧进行动态物体分割，在运行时也可以仅使用单帧信息，但是动态物体分割性能不如多帧。更多信息可以在我们的论文中找到，[论文链接](http://www.ipb.uni-bonn.de/pdfs/chen2021ral-iros.pdf)。

Q: Does LiDAR-MOS need sequential LiDAR scans with poses or it can also use only one scan?
A: Our LiDAR-MOS uses past sequential information to segment the moving object in the current frame. It can also use only one frame to achieve moving object segmentation. However, the MOS performance is worse than with multiple scans. More details can be found in the corresponding [paper](http://www.ipb.uni-bonn.de/pdfs/chen2021ral-iros.pdf).
